// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Estifanos Endale",
    email: "estifanos@test.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "Jimma, Ethiopia",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Helen Demelash",
    email: "helen@test.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "Jimma, Ethiopia",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mulugeta Getachew",
    email: "mulugeta@test.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Jimma, Ethiopia",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "2322",
    name: "Yoseph Lemma",
    email: "yoseph@test.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0913212233",
    grade: 5,
    class: "1B",
    address: "Jimma, Ethiopia",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Kalkidan Tesema",
    email: "kalkidan@test.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "093442422",
    grade: 5,
    class: "5A",
    address: "Jimma, Ethiopia",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Ali Mohammed",
    email: "ali@test.com",
    photo:
    "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0955223322",
    grade: 5,
    class: "5A",
    address: "Jimma, Ethiopia",
  },
  
];

export const parentsData = [
  {
    id: 1,
    name: "Abebe Kebede",
    students: ["Lemlem Abebe"],
    email: "abebe@kebede.com",
    phone: "+251911223344",
    address: "Jimma, Ethiopia",
  },
  {
    id: 2,
    name: "Almaz Alemu",
    students: ["Meklit Tadesse"],
    email: "almaz@alemu.com",
    phone: "+251922334455",
    address: "Jimma, Ethiopia",
  },
  {
    id: 3,
    name: "Bekele Wolde",
    students: ["Aster Bekele"],
    email: "bekele@wolde.com",
    phone: "+251933445566",
    address: "Jimma, Ethiopia",
  },
  {
    id: 4,
    name: "Dawit Gebre",
    students: ["Hana Dawit", "Biruk Dawit"],
    email: "dawit@gebre.com",
    phone: "+251944556677",
    address: "Jimma, Ethiopia",
  },
  {
    id: 5,
    name: "Fikirte Mesfin",
    students: ["Tigist Tadesse"],
    email: "fikirte@mesfin.com",
    phone: "+251955667788",
    address: "Jimma, Ethiopia",
  },
  {
    id: 6,
    name: "Genet Tsegaye",
    students: ["Yonas Abebe"],
    email: "genet@tsegaye.com",
    phone: "+251966778899",
    address: "Jimma, Ethiopia",
  },
  {
    id: 7,
    name: "Haile Yohannes",
    students: ["Mulu Haile", "Selam Haile"],
    email: "haile@yohannes.com",
    phone: "+251977889900",
    address: "Jimma, Ethiopia",
  },
  {
    id: 8,
    name: "Kidist Melaku",
    students: ["Adanech Girma"],
    email: "kidist@melaku.com",
    phone: "+251988990011",
    address: "Jimma, Ethiopia",
  },
  {
    id: 9,
    name: "Lidetu Kassaye",
    students: ["Tsehay Lidetu", "Wubit Lidetu"],
    email: "lidetu@kassaye.com",
    phone: "+251999001122",
    address: "Jimma, Ethiopia",
  },
  {
    id: 10,
    name: "Mulugeta Mekonnen",
    students: ["Hirut Mulugeta"],
    email: "mulugeta@mekonnen.com",
    phone: "+251910112233",
    address: "Jimma, Ethiopia",
  },
];


export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Kebede Teshome", "Biruk Getachew"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Mekonnen Alemayehu", "Tewodros Melaku"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Selamawit Hailu", "Abebe Fikre"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Tsegaye Tesfaye", "Girma Bekele"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Aster Gebremariam", "Lemlem Desta"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hirut Alemu", "Mulu Gebre"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Genet Fekadu", "Bekele Solomon"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Kidist Zewdu", "Meaza Mengistu"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Tigist Assefa", "Yonas Kebede"],
  },
];


export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Abebe Kebede",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Mekonnen Alemayehu",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tsegaye Tesfaye",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Yonas Hailu",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Lemlem Desta",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Kidist Zewdu",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Biruk Getachew",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Genet Fekadu",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Aberash Yohannes",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Fitsum Demeke",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Kebede Teshome",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Hana Alemu",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tigist Fikre",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Tadesse Mekonnen",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Kidist Zewdu",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Meaza Desta",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Yonas Bekele",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Genet Tadesse",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Abebe Fikadu",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Lemlem Hailu",
  },
];


export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Kebede Teshome",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Hana Alemu",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tigist Fikre",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Tadesse Mekonnen",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Kidist Zewdu",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Meaza Desta",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Yonas Bekele",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Genet Tadesse",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Abebe Fikadu",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Lemlem Hailu",
    date: "2025-01-01",
  },
];


export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Kebede Teshome",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Hana Alemu",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tigist Fikre",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Tadesse Mekonnen",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Kidist Zewdu",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Meaza Desta",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Yonas Bekele",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Genet Tadesse",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Abebe Fikadu",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Lemlem Hailu",
    dueDate: "2025-01-01",
  },
];


export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Kebede Teshome",
    student: "Lemlem Abebe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Hana Alemu",
    student: "Meklit Tadesse",
    date: "2025-01-01",
    type: "exam",
    score: 85,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Tigist Fikre",
    student: "Aster Bekele",
    date: "2025-01-01",
    type: "exam",
    score: 88,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Tadesse Mekonnen",
    student: "Biruk Dawit",
    date: "2025-01-01",
    type: "exam",
    score: 92,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Kidist Zewdu",
    student: "Tigist Tadesse",
    date: "2025-01-01",
    type: "exam",
    score: 87,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Meaza Desta",
    student: "Yonas Abebe",
    date: "2025-01-01",
    type: "exam",
    score: 93,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Yonas Bekele",
    student: "Mulu Haile",
    date: "2025-01-01",
    type: "exam",
    score: 89,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Genet Tadesse",
    student: "Adanech Girma",
    date: "2025-01-01",
    type: "exam",
    score: 91,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Abebe Fikadu",
    student: "Tsehay Lidetu",
    date: "2025-01-01",
    type: "exam",
    score: 88,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Lemlem Hailu",
    student: "Hirut Mulugeta",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];


export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];

// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 9, 6, 8, 0),
    end: new Date(2024, 9, 6, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 6, 9, 0),
    end: new Date(2024, 9, 6, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 6, 10, 0),
    end: new Date(2024, 9, 6, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 6, 13, 0),
    end: new Date(2024, 9, 6, 13, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 9, 6, 14, 0),
    end: new Date(2024, 9, 6, 14, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 6, 15, 0),
    end: new Date(2024, 9, 6, 15, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 7, 9, 0),
    end: new Date(2024, 9, 7, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 7, 10, 0),
    end: new Date(2024, 9, 7, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 7, 11, 0),
    end: new Date(2024, 9, 7, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 7, 14, 0),
    end: new Date(2024, 9, 7, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 9, 9, 8, 0),
    end: new Date(2024, 9, 9, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 9, 10, 0),
    end: new Date(2024, 9, 9, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 9, 9, 13, 0),
    end: new Date(2024, 9, 9, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 9, 14, 0),
    end: new Date(2024, 9, 9, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 11, 9, 0),
    end: new Date(2024, 9, 11, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 11, 10, 0),
    end: new Date(2024, 9, 11, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 11, 11, 0),
    end: new Date(2024, 9, 11, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 11, 14, 0),
    end: new Date(2024, 9, 11, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 9, 16, 8, 0),
    end: new Date(2024, 9, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 16, 9, 0),
    end: new Date(2024, 9, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 16, 11, 0),
    end: new Date(2024, 9, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 9, 16, 13, 0),
    end: new Date(2024, 9, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 16, 14, 0),
    end: new Date(2024, 9, 16, 14, 45),
  },
];
